PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

# streams in Orange County
SELECT ?stream ?streamLabel WHERE {
  VALUES ?county { wd:Q507957 }      
  VALUES ?types  {                           
    wd:Q47521    
    wd:Q355304  
    wd:Q685150   
    wd:Q12284    
  }

  ?stream wdt:P131* ?county .
  ?stream wdt:P31 ?type .
  FILTER(?type IN (?types))

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY ?streamLabel
