PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

# top ten most 
SELECT DISTINCT ?swamp ?swampLabel ?elevation ?location
WHERE {
  # counties in North Carolina
  ?county wdt:P31 wd:Q13414758 .

  ?swamp wdt:P131* ?county ;
         wdt:P31/wdt:P279* wd:Q166735 ;
         wdt:P625 ?location ;
         wdt:P2044 ?elevation .

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY DESC(?elevation)
limit 10