PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ex: <http://example.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?s dcterms:title       ?label ;
     dcterms:description ?comment .
}
WHERE {
  OPTIONAL { ?s rdfs:label   ?label . }
  OPTIONAL { ?s rdfs:comment ?comment . }
}
